"""Generate every Jupyter notebook for Week 1.

The notebooks are emitted as plain nbformat-4 JSON. Running this script is
idempotent: it always rewrites the files from the source-of-truth content
defined below. Keeping notebook content in this file (rather than 21 hand-edited
.ipynb blobs) makes course updates a one-edit operation.

Usage:
    python3 scripts/build_week01_notebooks.py
"""
from __future__ import annotations

import json
import textwrap
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
WEEK1 = ROOT / "weeks" / "week-01-foundations"


def md(*lines: str) -> dict:
    text = "\n".join(lines)
    return {"cell_type": "markdown", "metadata": {}, "source": text.splitlines(keepends=True)}


def code(*lines: str) -> dict:
    text = textwrap.dedent("\n".join(lines)).strip("\n") + "\n"
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": text.splitlines(keepends=True),
    }


# Every notebook starts with this snippet so `from shared.data_utils import ...`
# works regardless of how deeply nested the notebook is. We walk up the
# directory tree until we hit the repo's pyproject.toml.
REPO_ROOT_BOOTSTRAP = (
    "import sys, pathlib",
    "p = pathlib.Path.cwd()",
    "while not (p / 'pyproject.toml').exists() and p != p.parent:",
    "    p = p.parent",
    "if str(p) not in sys.path:",
    "    sys.path.insert(0, str(p))",
)


def write_nb(path: Path, cells: list[dict]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    nb = {
        "cells": cells,
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python", "version": "3.11"},
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }
    path.write_text(json.dumps(nb, indent=1, ensure_ascii=False) + "\n")


# ============================================================================
# COURSE 1 — NUMPY
# ============================================================================

def course1_lecture() -> list[dict]:
    return [
        md("# Course 1 — The Numerical Engine (NumPy)",
           "",
           "Live-coding notebook that mirrors the slide deck.",
           "Concrete examples lifted from Aurélien Géron's NumPy tutorial.",
           "",
           "**Sections**",
           "1. The ND-Array (0:00–0:30)",
           "2. Shape & Slicing (0:30–1:00)",
           "3. Vectorize (1:00–1:30)"),
        code("import numpy as np",
             "np.__version__"),
        md("## 1. The ND-Array"),
        md("### List vs. ndarray — same data, different machine"),
        code("py_list = [1, 2, 3, 4]",
             "arr = np.array([1, 2, 3, 4])",
             "print(py_list, type(py_list))",
             "print(arr, type(arr), arr.dtype)"),
        md("### Measure it"),
        code("%timeit sum(range(1_000_000))",
             "%timeit np.arange(1_000_000).sum()"),
        md("### Creating arrays — the recipes you'll use weekly"),
        code("print(np.zeros(5))",
             "print(np.zeros((3, 4)))",
             "print(np.ones((3, 4)))",
             "print(np.full((3, 4), np.pi))"),
        code("print(np.arange(1, 5))",
             "print(np.arange(1, 5, 0.5))",
             "print(np.linspace(0, 5/3, 6))",
             "print(np.eye(3))"),
        code("rng = np.random.default_rng(seed=42)",
             "print(rng.random((3, 4)))",
             "print(rng.standard_normal((3, 4)))"),
        md("### dtypes — promotion in action"),
        code("c = np.arange(1, 5)",
             "print(c.dtype, c)        # int64",
             "",
             "k1 = np.arange(0, 5, dtype=np.uint8)",
             "k2 = k1 + np.array([5, 6, 7, 8, 9], dtype=np.int8)",
             "print(k2.dtype, k2)      # int16",
             "",
             "k3 = k1 + 1.5",
             "print(k3.dtype, k3)      # float64"),
        md("### Inspect any array in six attributes"),
        code("a = np.zeros((3, 4))",
             "print(a.shape, a.ndim, a.size, a.itemsize, a.nbytes, a.dtype)"),
        md("## 2. Shape & Slicing"),
        md("### Reshape, ravel, transpose"),
        code("g = np.arange(24)",
             "g.shape = (6, 4)            # reshape in place",
             "print(g)",
             "",
             "g2 = g.reshape(4, 6)        # new view, same buffer",
             "print(g2)",
             "",
             "print(g.ravel())            # back to 1-D"),
        code("t = np.arange(24).reshape(4, 2, 3)",
             "print(t.transpose((1, 2, 0)).shape)   # (2, 3, 4)",
             "",
             "m1 = np.arange(10).reshape(2, 5)",
             "print(m1.T)"),
        md("### 2-D slicing — the main move"),
        code("b = np.arange(48).reshape(4, 12)",
             "print(b)",
             "print('b[1, 2]   =', b[1, 2])",
             "print('b[1, :]   =', b[1, :])",
             "print('b[:, 1]   =', b[:, 1])",
             "print('b[1:3,2:5]=\\n', b[1:3, 2:5])",
             "print('b[::-1]   =\\n', b[::-1])"),
        md("### Fancy indexing — pick whatever rows/cols you want"),
        code("print(b[(0, 2), 2:5])                       # rows 0 and 2, cols 2-4",
             "print(b[:, (-1, 2, -1)])                     # cols last, 2, last (repeats!)",
             "print(b[(-1, 2, -1, 2), (5, 9, 1, 9)])       # paired indices — 4 cells"),
        md("### Boolean indexing"),
        code("m = np.array([20, -5, 30, 40])",
             "print(m[m < 25])             # [20 -5]",
             "",
             "rows_on = np.array([True, False, True, False])",
             "print(b[rows_on, :])         # keep rows 0 and 2",
             "",
             "print(b[b % 3 == 1])         # every elem where x%3 == 1"),
        md("### Gotcha: slices are *views*"),
        code("a = np.arange(12).reshape(3, 4)",
             "view = a[:2, :2]",
             "view[0, 0] = -999",
             "print(a)        # the source mutated too!"),
        md("## 3. Vectorize"),
        md("### The loop you stop writing"),
        code("rng = np.random.default_rng(0)",
             "x = rng.normal(size=1_000_000)",
             "",
             "def slow(x):",
             "    out = np.empty_like(x)",
             "    for i in range(len(x)):",
             "        out[i] = x[i]**2 + 3*x[i]",
             "    return out",
             "",
             "def fast(x):",
             "    return x**2 + 3*x",
             "",
             "%timeit slow(x)",
             "%timeit fast(x)"),
        md("### Element-wise arithmetic on paired arrays"),
        code("a = np.array([14, 23, 32, 41])",
             "b = np.array([5,  4,  3,  2])",
             "print(a + b)",
             "print(a - b)",
             "print(a * b)",
             "print(a / b)",
             "print(np.maximum(a, b))",
             "print(np.greater(a, b))"),
        md("### Universal functions — math everywhere"),
        code("print(np.sqrt(a))",
             "print(np.exp(a))",
             "print(np.sin(a))",
             "print(np.maximum(a, 0))     # ReLU in one line",
             "print(np.clip(a, 0, 30))"),
        md("### Reductions — and the axis mnemonic"),
        code("a = np.array([[-2.5, 3.1, 7], [10, 11, 12]])",
             "print('mean all   :', a.mean())",
             "",
             "c = np.arange(24).reshape(2, 3, 4)",
             "print('sum axis 0 :', c.sum(axis=0).shape)   # collapse axis 0 -> (3, 4)",
             "print('sum axis 1 :', c.sum(axis=1).shape)   # collapse axis 1 -> (2, 4)",
             "print('sum (0, 2) :', c.sum(axis=(0, 2)).shape)"),
        md("### Broadcasting — three live examples"),
        code("k = np.arange(6).reshape(2, 3)",
             "print(k)",
             "",
             "# (2,3) + (3,) -> broadcast row across both rows",
             "print(k + [100, 200, 300])",
             "",
             "# (2,3) + (2,1) -> broadcast column across cols",
             "print(k + [[100], [200]])",
             "",
             "# (1,1,5) + (5,) -> still (1,1,5)",
             "h = np.arange(5).reshape(1, 1, 5)",
             "print(h + [10, 20, 30, 40, 50])"),
        md("### Matrix multiplication"),
        code("n1 = np.arange(10).reshape(2, 5)",
             "n2 = np.arange(15).reshape(5, 3)",
             "print(n1.dot(n2))   # equivalent to n1 @ n2"),
        md("### Linear algebra"),
        code("import numpy.linalg as linalg",
             "",
             "m = np.array([[1,  2,  3],",
             "              [5,  7, 11],",
             "              [21, 29, 31]])",
             "print('inv:\\n', linalg.inv(m))",
             "print('det:', linalg.det(m))",
             "",
             "A = np.array([[2, 6], [5, 3]])",
             "b_vec = np.array([6, -9])",
             "print('solve Ax=b:', linalg.solve(A, b_vec))   # [-3.  2.]"),
        md("### Worked example — standardize a data matrix"),
        code("rng = np.random.default_rng(0)",
             "X = rng.normal(loc=5, scale=2, size=(200, 5))",
             "Z = (X - X.mean(axis=0)) / X.std(axis=0)",
             "print('column means ~0:', Z.mean(axis=0).round(4))",
             "print('column stds  ~1:', Z.std(axis=0).round(4))"),
        md("### Recap",
           "* ndarray is a contiguous typed buffer — that is the entire speed story.",
           "* Reshape and transpose change *strides*, not data.",
           "* Replace numeric `for` loops with broadcasting + reductions."),
    ]


def course1_ex1_starter() -> list[dict]:
    return [
        md("# Exercise 1 — Array Basics",
           "",
           "Goal: get fluent with creation, dtypes, and the shape vocabulary."),
        code("import numpy as np",
             "rng = np.random.default_rng(42)"),
        md("**Task 1.** Create a `(4, 5)` array of zeros with dtype `int32`. Print its shape, dtype, and total memory in bytes."),
        code("# your code here"),
        md("**Task 2.** Build a 1-D array of 50 evenly-spaced values between -3 and 3 inclusive."),
        code("# your code here"),
        md("**Task 3.** Draw 10000 standard-normal samples. Compute the empirical mean and std and check they are close to 0 and 1."),
        code("# your code here"),
        md("**Task 4.** Make a `(3, 3)` identity matrix without using `np.eye`. (Hint: `np.arange` + boolean comparison.)"),
        code("# your code here"),
    ]


def course1_ex1_solution() -> list[dict]:
    return [
        md("# Exercise 1 — Solutions"),
        code("import numpy as np",
             "rng = np.random.default_rng(42)"),
        md("**Task 1.**"),
        code("a = np.zeros((4, 5), dtype=np.int32)",
             "print(a.shape, a.dtype, a.nbytes, 'bytes')"),
        md("**Task 2.**"),
        code("xs = np.linspace(-3, 3, 50)",
             "print(xs[:5], '...', xs[-5:])",
             "print('count:', xs.size)"),
        md("**Task 3.**"),
        code("samples = rng.normal(size=10_000)",
             "print('mean:', samples.mean(), '  std:', samples.std())",
             "assert abs(samples.mean()) < 0.05",
             "assert abs(samples.std() - 1) < 0.05"),
        md("**Task 4.**"),
        code("n = 3",
             "ix = np.arange(n)",
             "I = (ix[:, None] == ix[None, :]).astype(int)",
             "print(I)",
             "assert np.array_equal(I, np.eye(n, dtype=int))"),
    ]


def course1_ex2_starter() -> list[dict]:
    return [
        md("# Exercise 2 — Slicing & Reshape",
           "",
           "We will treat an image as an ndarray — exactly what every CV model sees."),
        code("import numpy as np",
             "import matplotlib.pyplot as plt",
             "rng = np.random.default_rng(0)",
             "",
             "# Synthetic 'image': a 64x64 grayscale gradient with a bright square in the center.",
             "img = np.tile(np.linspace(0, 1, 64), (64, 1))",
             "img[24:40, 24:40] = 1.0",
             "plt.imshow(img, cmap='gray'); plt.title('source'); plt.axis('off');"),
        md("**Task 1.** Crop the central 32×32 region of `img` and display it."),
        code("# your code here"),
        md("**Task 2.** Flip the image left↔right and top↔bottom (two separate outputs)."),
        code("# your code here"),
        md("**Task 3.** Convert the image to RGB by stacking it 3 times along a new last axis. Print the new shape."),
        code("# your code here"),
        md("**Task 4.** Set every pixel whose value is above 0.9 to 0 (in a copy, not the original)."),
        code("# your code here"),
    ]


def course1_ex2_solution() -> list[dict]:
    return [
        md("# Exercise 2 — Solutions"),
        code("import numpy as np",
             "import matplotlib.pyplot as plt",
             "rng = np.random.default_rng(0)",
             "img = np.tile(np.linspace(0, 1, 64), (64, 1))",
             "img[24:40, 24:40] = 1.0"),
        md("**Task 1.** Center crop."),
        code("crop = img[16:48, 16:48]",
             "print(crop.shape)",
             "plt.imshow(crop, cmap='gray'); plt.axis('off');"),
        md("**Task 2.** Flips."),
        code("lr = img[:, ::-1]",
             "ud = img[::-1, :]",
             "fig, ax = plt.subplots(1, 2, figsize=(6, 3))",
             "ax[0].imshow(lr, cmap='gray'); ax[0].set_title('LR'); ax[0].axis('off')",
             "ax[1].imshow(ud, cmap='gray'); ax[1].set_title('UD'); ax[1].axis('off');"),
        md("**Task 3.** Grayscale -> RGB."),
        code("rgb = np.stack([img, img, img], axis=-1)",
             "print(rgb.shape)        # (64, 64, 3)"),
        md("**Task 4.** Threshold on a copy."),
        code("out = img.copy()",
             "out[out > 0.9] = 0",
             "print('max before:', img.max(), 'max after:', out.max())"),
    ]


def course1_ex3_starter() -> list[dict]:
    return [
        md("# Exercise 3 — Vectorization & Broadcasting",
           "",
           "Replace every `for` loop with a vectorized expression."),
        code("import numpy as np",
             "rng = np.random.default_rng(0)",
             "x = rng.normal(size=1_000_000)"),
        md("**Task 1.** Compute the per-element sigmoid `1 / (1 + exp(-x))` for `x` — no loops."),
        code("# your code here"),
        md("**Task 2.** Standardize a `(200, 5)` data matrix column-wise (subtract column mean, divide by column std)."),
        code("data = rng.normal(loc=5, scale=2, size=(200, 5))",
             "# your code here"),
        md("**Task 3.** Given 50 2-D points in `pts`, compute the full 50×50 pairwise Euclidean distance matrix. No loops."),
        code("pts = rng.normal(size=(50, 2))",
             "# your code here"),
        md("**Task 4 (stretch).** Time a Python-loop version of Task 3 vs your vectorized version with `%timeit`."),
        code("# your code here"),
    ]


def course1_ex3_solution() -> list[dict]:
    return [
        md("# Exercise 3 — Solutions"),
        code("import numpy as np",
             "rng = np.random.default_rng(0)",
             "x = rng.normal(size=1_000_000)"),
        md("**Task 1.**"),
        code("sig = 1 / (1 + np.exp(-x))",
             "print(sig[:5])"),
        md("**Task 2.** Column-wise standardize."),
        code("data = rng.normal(loc=5, scale=2, size=(200, 5))",
             "z = (data - data.mean(axis=0)) / data.std(axis=0)",
             "print('column means ~0:', z.mean(axis=0).round(4))",
             "print('column stds  ~1:', z.std(axis=0).round(4))"),
        md("**Task 3.** Pairwise distances."),
        code("pts = rng.normal(size=(50, 2))",
             "diff = pts[:, None, :] - pts[None, :, :]",
             "dist = np.sqrt((diff**2).sum(axis=-1))",
             "print(dist.shape)",
             "assert np.allclose(dist, dist.T)",
             "assert np.allclose(np.diag(dist), 0)"),
        md("**Task 4.** Timing showdown."),
        code("def naive(pts):",
             "    n = len(pts)",
             "    out = np.empty((n, n))",
             "    for i in range(n):",
             "        for j in range(n):",
             "            out[i, j] = np.sqrt(((pts[i] - pts[j])**2).sum())",
             "    return out",
             "",
             "def fast(pts):",
             "    diff = pts[:, None, :] - pts[None, :, :]",
             "    return np.sqrt((diff**2).sum(axis=-1))",
             "",
             "%timeit naive(pts)",
             "%timeit fast(pts)"),
    ]


# ============================================================================
# COURSE 2 — PANDAS
# ============================================================================

def course2_lecture() -> list[dict]:
    return [
        md("# Course 2 — Data Manipulation (Pandas)",
           "",
           "Live-coding notebook that mirrors the slide deck.",
           "Concrete examples lifted from Aurélien Géron's Pandas tutorial.",
           "",
           "**Sections**",
           "1. Series & DataFrames (0:00–0:30)",
           "2. Select & Filter (0:30–1:00)",
           "3. Clean, Group, Join (1:00–1:30)"),
        code(
            "import sys, pathlib",
            "p = pathlib.Path.cwd()",
            "while not (p / 'pyproject.toml').exists() and p != p.parent:",
            "    p = p.parent",
            "if str(p) not in sys.path:",
            "    sys.path.insert(0, str(p))",
             "import pandas as pd",
             "import numpy as np",
             "pd.__version__"),
        md("## 1. Series & DataFrames"),
        md("### Series — your first one"),
        code("s = pd.Series([2, -1, 3, 5])",
             "s"),
        md("### NumPy plus labels"),
        code("np.exp(s)"),
        code("s + [1000, 2000, 3000, 4000]"),
        code("s + 1000      # scalar broadcasts"),
        code("s < 0         # element-wise comparison"),
        md("### Index labels — name your rows"),
        code("s2 = pd.Series([68, 83, 112, 68], index=['alice', 'bob', 'charles', 'darwin'])",
             "s2"),
        code("print(s2['bob'])",
             "print(s2.loc['bob'])",
             "print(s2.iloc[1])"),
        md("### Gotcha — default-int labels are *labels*, not positions"),
        code("surprise = pd.Series([1000, 1001, 1002, 1003])",
             "slice_ = surprise[2:]",
             "print(slice_)",
             "",
             "try:",
             "    slice_[0]",
             "except KeyError as e:",
             "    print('Key error:', e)",
             "",
             "print('via iloc:', slice_.iloc[0])"),
        md("### Build from a dict"),
        code("weights = {'alice': 68, 'bob': 83, 'colin': 86, 'darwin': 68}",
             "s3 = pd.Series(weights)",
             "s3"),
        md("### Automatic alignment"),
        code("print(s2.keys())",
             "print(s3.keys())",
             "s2 + s3"),
        md("### Build a DataFrame — from Series"),
        code("people_dict = {",
             "    'weight':    pd.Series([68, 83, 112], index=['alice', 'bob', 'charles']),",
             "    'birthyear': pd.Series([1984, 1985, 1992],",
             "                           index=['bob', 'alice', 'charles'], name='year'),",
             "    'children':  pd.Series([0, 3], index=['charles', 'bob']),",
             "    'hobby':     pd.Series(['Biking', 'Dancing'], index=['alice', 'bob']),",
             "}",
             "people = pd.DataFrame(people_dict)",
             "people"),
        md("### Build a DataFrame — from values + labels"),
        code("values = [[1985, np.nan, 'Biking',  68],",
             "          [1984, 3,      'Dancing', 83],",
             "          [1992, 0,       np.nan,  112]]",
             "d3 = pd.DataFrame(values,",
             "                  columns=['birthyear', 'children', 'hobby', 'weight'],",
             "                  index=['alice', 'bob', 'charles'])",
             "d3"),
        md("### The first three things on any fresh dataset"),
        code("people.head()"),
        code("people.info()"),
        code("people.describe(include='all')"),
        md("## 2. Select & Filter"),
        md("### Columns"),
        code("people['birthyear']"),
        code("people[['birthyear', 'hobby']]"),
        md("### Rows — three ways"),
        code("people.loc['charles']"),
        code("people.iloc[2]"),
        code("people.iloc[1:3]"),
        code("people[np.array([True, False, True])]"),
        code("people[people['birthyear'] < 1990]"),
        md("### Boolean masks compose with `&` / `|` / `~`"),
        code("people[(people['birthyear'] < 1990) & (people['weight'] > 70)]"),
        code("people[people['hobby'].isin(['Biking', 'Dancing'])]"),
        code("people[~people['hobby'].isna()]"),
        md("### Cleaner: `.query`"),
        code("people['age'] = 2025 - people['birthyear']",
             "people['pets'] = pd.Series({'bob': 0, 'charles': 5})",
             "people.query('age > 30 and pets == 0')"),
        md("### Add & drop columns"),
        code("people['over 30'] = people['age'] > 30",
             "people.insert(1, 'height', [172, 181, 185])",
             "people"),
        md("### `.assign` — chainable feature engineering"),
        code("(people",
             "   .assign(bmi      = lambda df: df['weight'] / (df['height'] / 100) ** 2)",
             "   .assign(overwt   = lambda df: df['bmi'] > 25)",
             ")"),
        md("### Sorting"),
        code("people.sort_values(by='age')"),
        md("## 3. Clean, Group, Join"),
        md("### Build two frames with mismatched labels"),
        code("grades_array = np.array([[8, 8, 9], [10, 9, 9], [4, 8, 2], [9, 10, 10]])",
             "grades = pd.DataFrame(grades_array,",
             "                      columns=['sep', 'oct', 'nov'],",
             "                      index=['alice', 'bob', 'charles', 'darwin'])",
             "grades"),
        code("bonus = pd.DataFrame(",
             "    [[0, np.nan, 2], [np.nan, 1, 0], [0, 1, 0], [3, 3, 0]],",
             "    columns=['oct', 'nov', 'dec'],",
             "    index=['bob', 'colin', 'darwin', 'charles'])",
             "bonus"),
        code("(grades + bonus)         # aligned by label; missing pairs -> NaN"),
        md("### Fill vs drop"),
        code("(grades + bonus).fillna(0)"),
        code("(grades + bonus).dropna(how='all')"),
        md("### Interpolate"),
        code("bonus.interpolate(axis=1)"),
        md("### groupby — the workhorse"),
        code("final = (grades + bonus).fillna(0)",
             "final['hobby'] = ['Biking', 'Dancing', np.nan, 'Dancing', 'Biking']",
             "final"),
        code("final.groupby('hobby').mean(numeric_only=True)   # NaN groups skipped"),
        code("final.groupby('hobby').agg(",
             "    n      = ('sep', 'size'),",
             "    sep_mu = ('sep', 'mean'),",
             "    nov_std= ('nov', 'std'),",
             ")"),
        md("### transform — aggregate but keep original shape"),
        code("final['nov_z'] = (",
             "    final.groupby('hobby')['nov']",
             "         .transform(lambda x: (x - x.mean()) / x.std())",
             ")",
             "final"),
        md("### Pivot tables"),
        code("more = final.reset_index().melt(id_vars=['index', 'hobby'],",
             "                                value_vars=['sep', 'oct', 'nov'],",
             "                                var_name='month', value_name='grade')",
             "more = more.rename(columns={'index': 'name'})",
             "more.head()"),
        code("pd.pivot_table(more, index='name', values='grade',",
             "               columns='month', margins=True)"),
        md("### SQL-style joins"),
        code("city_loc = pd.DataFrame(",
             "    [['CA', 'San Francisco', 37.78, -122.42],",
             "     ['NY', 'New York',      40.71,  -74.01],",
             "     ['FL', 'Miami',         25.79,  -80.32]],",
             "    columns=['state', 'city', 'lat', 'lng'])",
             "",
             "city_pop = pd.DataFrame(",
             "    [[ 808976, 'San Francisco', 'California'],",
             "     [8363710, 'New York',      'New-York'],",
             "     [2242193, 'Houston',       'Texas']],",
             "    columns=['population', 'city', 'state'])",
             "",
             "pd.merge(city_loc, city_pop, on='city')               # INNER"),
        code("pd.merge(city_loc, city_pop, on='city', how='outer')  # OUTER"),
        md("### Concatenation"),
        code("pd.concat([city_loc, city_pop], ignore_index=True)"),
        md("### Time series — one minute tour"),
        code("temps = [4.4, 5.1, 6.1, 6.2, 6.1, 6.1, 5.7, 5.2, 4.7, 4.1, 3.9, 3.5]",
             "dates = pd.date_range('2016/10/29 5:30pm', periods=12, freq='h')",
             "ts = pd.Series(temps, index=dates, name='Temperature')",
             "ts.head()"),
        code("ts.resample('2h').mean()"),
        code("ts.resample('15min').interpolate(method='cubic').head()"),
        md("### Recap",
           "* Series = labeled NumPy array. DataFrame = dict of aligned Series.",
           "* `.loc` for labels, `.iloc` for positions, masks & `.query` for filters.",
           "* Group, aggregate, derive — in chained pipelines."),
    ]


def course2_ex1_starter() -> list[dict]:
    return [
        md("# Exercise 1 — DataFrame I/O & Inspection"),
        code(
            "import sys, pathlib",
            "p = pathlib.Path.cwd()",
            "while not (p / 'pyproject.toml').exists() and p != p.parent:",
            "    p = p.parent",
            "if str(p) not in sys.path:",
            "    sys.path.insert(0, str(p))",
             "from shared.data_utils import load_dataset",
             "import pandas as pd"),
        md("**Task 1.** Load the `tips` dataset. Show the first 5 rows and the dtypes."),
        code("# your code here"),
        md("**Task 2.** How many rows and columns does it have? How many numeric columns?"),
        code("# your code here"),
        md("**Task 3.** Print a 5-number summary (`describe()`) for the numeric columns only."),
        code("# your code here"),
        md("**Task 4.** Set the index to a new column `bill_id` (just a 0-based range)."),
        code("# your code here"),
    ]


def course2_ex1_solution() -> list[dict]:
    return [
        md("# Exercise 1 — Solutions"),
        code(
            "import sys, pathlib",
            "p = pathlib.Path.cwd()",
            "while not (p / 'pyproject.toml').exists() and p != p.parent:",
            "    p = p.parent",
            "if str(p) not in sys.path:",
            "    sys.path.insert(0, str(p))",
             "from shared.data_utils import load_dataset",
             "import pandas as pd",
             "df = load_dataset('tips')"),
        md("**Task 1.**"),
        code("print(df.head())",
             "print(df.dtypes)"),
        md("**Task 2.**"),
        code("print('shape:', df.shape)",
             "print('numeric cols:', df.select_dtypes('number').columns.tolist())"),
        md("**Task 3.**"),
        code("df.describe()"),
        md("**Task 4.**"),
        code("df = df.assign(bill_id=range(len(df))).set_index('bill_id')",
             "df.head()"),
    ]


def course2_ex2_starter() -> list[dict]:
    return [
        md("# Exercise 2 — Selection & Filtering"),
        code(
            "import sys, pathlib",
            "p = pathlib.Path.cwd()",
            "while not (p / 'pyproject.toml').exists() and p != p.parent:",
            "    p = p.parent",
            "if str(p) not in sys.path:",
            "    sys.path.insert(0, str(p))",
             "from shared.data_utils import load_dataset",
             "df = load_dataset('tips')"),
        md("**Task 1.** Select rows 10–19 (inclusive) and only the columns `total_bill`, `tip`, `day`. Use `.loc`."),
        code("# your code here"),
        md("**Task 2.** Find all dinners where the tip was at least 20% of the bill."),
        code("# your code here"),
        md("**Task 3.** Same as Task 2 but use `df.query(...)`."),
        code("# your code here"),
        md("**Task 4.** What is the average tip on weekends (Sat/Sun) vs weekdays?"),
        code("# your code here"),
    ]


def course2_ex2_solution() -> list[dict]:
    return [
        md("# Exercise 2 — Solutions"),
        code(
            "import sys, pathlib",
            "p = pathlib.Path.cwd()",
            "while not (p / 'pyproject.toml').exists() and p != p.parent:",
            "    p = p.parent",
            "if str(p) not in sys.path:",
            "    sys.path.insert(0, str(p))",
             "from shared.data_utils import load_dataset",
             "df = load_dataset('tips')"),
        md("**Task 1.**"),
        code("df.loc[10:19, ['total_bill', 'tip', 'day']]"),
        md("**Task 2.**"),
        code("mask = (df['time'] == 'Dinner') & (df['tip'] / df['total_bill'] >= 0.20)",
             "df[mask].head()"),
        md("**Task 3.**"),
        code("df.query('time == \"Dinner\" and tip / total_bill >= 0.20').head()"),
        md("**Task 4.**"),
        code("(df.assign(weekend=df['day'].isin(['Sat', 'Sun']))",
             "   .groupby('weekend')['tip'].mean().round(2))"),
    ]


def course2_ex3_starter() -> list[dict]:
    return [
        md("# Exercise 3 — Cleaning & Grouping"),
        code(
            "import sys, pathlib",
            "p = pathlib.Path.cwd()",
            "while not (p / 'pyproject.toml').exists() and p != p.parent:",
            "    p = p.parent",
            "if str(p) not in sys.path:",
            "    sys.path.insert(0, str(p))",
             "from shared.data_utils import load_dataset",
             "df = load_dataset('penguins')"),
        md("**Task 1.** Report the number of NaNs per column."),
        code("# your code here"),
        md("**Task 2.** Drop every row that has at least one NaN. How many rows did you lose?"),
        code("# your code here"),
        md("**Task 3.** On the cleaned data: per-species mean and std of `body_mass_g`. Round to 1 decimal."),
        code("# your code here"),
        md("**Task 4.** Add a column `mass_kg` (= body_mass_g / 1000) and a column `bill_ratio` (= bill_length / bill_depth). Sort by `bill_ratio` descending and show the top 5."),
        code("# your code here"),
    ]


def course2_ex3_solution() -> list[dict]:
    return [
        md("# Exercise 3 — Solutions"),
        code(
            "import sys, pathlib",
            "p = pathlib.Path.cwd()",
            "while not (p / 'pyproject.toml').exists() and p != p.parent:",
            "    p = p.parent",
            "if str(p) not in sys.path:",
            "    sys.path.insert(0, str(p))",
             "from shared.data_utils import load_dataset",
             "df = load_dataset('penguins')"),
        md("**Task 1.**"),
        code("df.isna().sum()"),
        md("**Task 2.**"),
        code("clean = df.dropna()",
             "print('lost', len(df) - len(clean), 'rows')"),
        md("**Task 3.**"),
        code("clean.groupby('species')['body_mass_g'].agg(['mean', 'std']).round(1)"),
        md("**Task 4.**"),
        code("clean = clean.assign(",
             "    mass_kg=clean['body_mass_g'] / 1000,",
             "    bill_ratio=clean['bill_length_mm'] / clean['bill_depth_mm'],",
             ")",
             "clean.sort_values('bill_ratio', ascending=False).head()"),
    ]


# ============================================================================
# COURSE 3 — VIZ + SCIPY
# ============================================================================

def course3_lecture() -> list[dict]:
    return [
        md("# Course 3 — Visualization & Math Bridge",
           "",
           "Matplotlib · Seaborn · SciPy.",
           "Concrete examples lifted from Aurélien Géron's Matplotlib tutorial.",
           "We end by *seeing* how an optimizer minimizes a function."),
        code(
            "import sys, pathlib",
            "p = pathlib.Path.cwd()",
            "while not (p / 'pyproject.toml').exists() and p != p.parent:",
            "    p = p.parent",
            "if str(p) not in sys.path:",
            "    sys.path.insert(0, str(p))",
             "import numpy as np",
             "import pandas as pd",
             "import matplotlib",
             "import matplotlib.pyplot as plt",
             "import seaborn as sns",
             "from scipy import stats, optimize",
             "rng = np.random.default_rng(seed=42)",
             "sns.set_theme(style='whitegrid')"),
        md("## 1. Matplotlib"),
        md("### Your first plot"),
        code("plt.plot([-3, -2, 5, 0], [1, 6, 4, 3])",
             "plt.show()"),
        md("### Plot a function"),
        code("x = np.linspace(-2, 2, 500)",
             "y = x**2",
             "plt.plot(x, y)",
             "plt.show()"),
        md("### Labels, title, grid, axis limits"),
        code("plt.plot(x, y)",
             "plt.title('Square function')",
             "plt.xlabel('x')",
             "plt.ylabel('y = x**2')",
             "plt.axis([-2.5, 2.5, 0, 5])",
             "plt.grid(True)",
             "plt.show()"),
        md("### Multiple curves on one axes"),
        code("plt.plot([0, 100, 100,   0,   0], [0,   0, 100, 100,   0], 'r-')",
             "plt.plot([0, 100,  50,   0, 100], [0, 100, 130, 100,   0], 'g--')",
             "plt.axis([-10, 110, -10, 140])",
             "plt.show()"),
        md("### Subplots — a 2x2 grid"),
        code("x = np.linspace(-1.4, 1.4, 30)",
             "plt.subplot(2, 2, 1); plt.plot(x, x);    plt.title('x')",
             "plt.subplot(2, 2, 2); plt.plot(x, x**2); plt.title('x^2')",
             "plt.subplot(2, 2, 3); plt.plot(x, x**3); plt.title('x^3')",
             "plt.subplot(2, 2, 4); plt.plot(x, x**4); plt.title('x^4')",
             "plt.tight_layout(); plt.show()"),
        md("### Scatter plot"),
        code("xs, ys = rng.random((2, 100))",
             "plt.scatter(xs, ys)",
             "plt.show()"),
        code("sizes = 200 * rng.random(100)",
             "plt.scatter(xs, ys, s=sizes, c=xs + ys, cmap='viridis', alpha=0.6)",
             "plt.colorbar(); plt.show()"),
        md("### Histogram"),
        code("data = [1, 1.1, 1.8, 2, 2.1, 3.2, 3, 3, 3, 3]",
             "plt.hist(data, bins=10, rwidth=0.8)",
             "plt.show()"),
        md("### Annotations — point at the interesting bit"),
        code("x = np.linspace(-1.5, 1.5, 30)",
             "px, py = 0.8, 0.64",
             "plt.plot(x, x**2, px, py, 'ro')",
             "plt.annotate('Beautiful point',",
             "             xy=(px, py), xytext=(px - 1.3, py + 0.5),",
             "             color='green', weight='heavy', fontsize=14,",
             "             arrowprops={'facecolor': 'lightgreen'})",
             "plt.show()"),
        md("### Contour — the 2-D loss landscape"),
        code("x = np.linspace(-5, 5, 50)",
             "y = np.linspace(-5, 5, 50)",
             "X, Y = np.meshgrid(x, y)",
             "Z = np.sin(np.sqrt(X**2 + Y**2))",
             "plt.contourf(X, Y, Z, cmap=matplotlib.cm.coolwarm)",
             "plt.colorbar(); plt.show()"),
        md("## 2. Seaborn — stats plots in one line"),
        code("tips = sns.load_dataset('tips')",
             "tips.head()"),
        code("sns.heatmap(tips.corr(numeric_only=True), annot=True, cmap='coolwarm', center=0);"),
        code("sns.kdeplot(data=tips, x='total_bill', hue='time', fill=True);"),
        code("sns.boxplot(data=tips, x='day', y='total_bill');"),
        md("## 3. SciPy — probability"),
        md("### Plot three Gaussians on one axes"),
        code("x = np.linspace(-4, 4, 200)",
             "for mu, sigma in [(0, 1), (0, 0.5), (1, 1)]:",
             "    plt.plot(x, stats.norm.pdf(x, mu, sigma), label=f'N({mu}, {sigma})')",
             "plt.legend(); plt.title('Normal PDFs'); plt.show()"),
        md("### Fit a Gaussian to data"),
        code("rng1 = np.random.default_rng(1)",
             "samples = rng1.normal(loc=2.0, scale=1.5, size=1000)",
             "mu_hat, sigma_hat = stats.norm.fit(samples)",
             "print(f'mu_hat = {mu_hat:.3f}, sigma_hat = {sigma_hat:.3f}')",
             "",
             "xs = np.linspace(samples.min(), samples.max(), 200)",
             "plt.hist(samples, bins=30, density=True, alpha=0.5)",
             "plt.plot(xs, stats.norm.pdf(xs, mu_hat, sigma_hat), lw=2, label='fitted')",
             "plt.legend(); plt.show()"),
        md("## 4. SciPy — optimization"),
        md("### The 1-D loss landscape"),
        code("f = lambda x: (x - 3)**2 + np.sin(5 * x)",
             "xs = np.linspace(-2, 8, 400)",
             "plt.plot(xs, f(xs))",
             "plt.title('A loss surface'); plt.xlabel('x'); plt.ylabel('loss'); plt.show()"),
        md("### Minimize — this is what models do"),
        code("res = optimize.minimize(f, x0=0.0)",
             "print('argmin =', res.x[0])",
             "print('min    =', res.fun)",
             "print('iters  =', res.nit)"),
        code("plt.plot(xs, f(xs))",
             "plt.axvline(res.x[0], color='red', ls='--', label=f'min at x={res.x[0]:.3f}')",
             "plt.legend(); plt.show()"),
        md("### Local minima — initialization matters"),
        code("res2 = optimize.minimize(f, x0=10.0)",
             "print('from x0=0  :', res.x[0])",
             "print('from x0=10 :', res2.x[0])"),
        md("### Takeaway",
           "Every supervised model: define a loss `L(parameters)` and call an optimizer. "
           "Today you saw the whole loop in 3 lines."),
        md("## Grand Finale — preview",
           "In the final exercise notebook you'll: load a messy stock-prices CSV, clean NaNs with pandas, compute a 7-day moving average with NumPy, and plot price + MA together with matplotlib."),
    ]


def course3_ex1_starter() -> list[dict]:
    return [
        md("# Exercise 1 — Matplotlib & Seaborn"),
        code(
            "import sys, pathlib",
            "p = pathlib.Path.cwd()",
            "while not (p / 'pyproject.toml').exists() and p != p.parent:",
            "    p = p.parent",
            "if str(p) not in sys.path:",
            "    sys.path.insert(0, str(p))",
             "import numpy as np",
             "import matplotlib.pyplot as plt",
             "import seaborn as sns",
             "from shared.data_utils import load_dataset",
             "rng = np.random.default_rng(7)",
             "sns.set_theme(style='whitegrid')"),
        md("**Task 1.** Plot `sin(x)` and `cos(x)` on the same axes for x in [-2π, 2π]. Add legend, axis labels and a title."),
        code("# your code here"),
        md("**Task 2.** Generate 300 points from two 2-D Gaussian blobs centered at `(0,0)` and `(3,3)`. Plot a scatter colored by cluster id."),
        code("# your code here"),
        md("**Task 3.** Load the `iris` dataset and draw a Seaborn heatmap of the correlation matrix of its numeric columns."),
        code("# your code here"),
        md("**Task 4.** Same dataset — KDE of `petal_length` colored by species."),
        code("# your code here"),
    ]


def course3_ex1_solution() -> list[dict]:
    return [
        md("# Exercise 1 — Solutions"),
        code(
            "import sys, pathlib",
            "p = pathlib.Path.cwd()",
            "while not (p / 'pyproject.toml').exists() and p != p.parent:",
            "    p = p.parent",
            "if str(p) not in sys.path:",
            "    sys.path.insert(0, str(p))",
             "import numpy as np",
             "import matplotlib.pyplot as plt",
             "import seaborn as sns",
             "from shared.data_utils import load_dataset",
             "rng = np.random.default_rng(7)",
             "sns.set_theme(style='whitegrid')"),
        md("**Task 1.**"),
        code("x = np.linspace(-2*np.pi, 2*np.pi, 400)",
             "plt.plot(x, np.sin(x), label='sin')",
             "plt.plot(x, np.cos(x), label='cos')",
             "plt.xlabel('x'); plt.ylabel('y'); plt.title('sin & cos'); plt.legend();"),
        md("**Task 2.**"),
        code("a = rng.normal(loc=[0, 0], size=(150, 2))",
             "b = rng.normal(loc=[3, 3], size=(150, 2))",
             "X = np.vstack([a, b]); y = np.r_[np.zeros(150), np.ones(150)]",
             "plt.scatter(X[:, 0], X[:, 1], c=y, cmap='viridis'); plt.title('two blobs');"),
        md("**Task 3.**"),
        code("iris = load_dataset('iris')",
             "sns.heatmap(iris.select_dtypes('number').corr(), annot=True, cmap='coolwarm');"),
        md("**Task 4.**"),
        code("sns.kdeplot(data=iris, x='petal_length', hue='species', fill=True);"),
    ]


def course3_ex2_starter() -> list[dict]:
    return [
        md("# Exercise 2 — SciPy stats & optimize"),
        code("import numpy as np",
             "import matplotlib.pyplot as plt",
             "from scipy import stats, optimize",
             "rng = np.random.default_rng(1)"),
        md("**Task 1.** Sample 1000 points from a `Normal(mean=2, std=1.5)` and fit a Gaussian back to them with `stats.norm.fit`. How close do you get?"),
        code("# your code here"),
        md("**Task 2.** Plot the histogram of those samples together with the *fitted* PDF."),
        code("# your code here"),
        md("**Task 3.** Minimize `f(x) = (x - 3)**2 + sin(x)` starting from `x0 = 0`. Report the argmin and the minimum value."),
        code("# your code here"),
        md("**Task 4 (stretch).** Show that starting from `x0 = 10` finds a *different* local minimum — this is why initialization matters."),
        code("# your code here"),
    ]


def course3_ex2_solution() -> list[dict]:
    return [
        md("# Exercise 2 — Solutions"),
        code("import numpy as np",
             "import matplotlib.pyplot as plt",
             "from scipy import stats, optimize",
             "rng = np.random.default_rng(1)"),
        md("**Task 1.**"),
        code("samples = rng.normal(loc=2.0, scale=1.5, size=1000)",
             "mu_hat, sigma_hat = stats.norm.fit(samples)",
             "print(f'fitted mean = {mu_hat:.3f},  fitted std = {sigma_hat:.3f}')"),
        md("**Task 2.**"),
        code("xs = np.linspace(samples.min(), samples.max(), 200)",
             "plt.hist(samples, bins=30, density=True, alpha=0.5)",
             "plt.plot(xs, stats.norm.pdf(xs, mu_hat, sigma_hat), lw=2, label='fitted PDF')",
             "plt.legend();"),
        md("**Task 3.**"),
        code("f = lambda x: (x - 3)**2 + np.sin(x)",
             "res = optimize.minimize(f, x0=0.0)",
             "print('argmin =', res.x[0], '  min =', res.fun)"),
        md("**Task 4.**"),
        code("res2 = optimize.minimize(f, x0=10.0)",
             "print('argmin from x0=10:', res2.x[0])",
             "xs = np.linspace(-2, 12, 500)",
             "plt.plot(xs, f(xs))",
             "plt.axvline(res.x[0], color='red', ls='--', label=f'from x0=0  -> {res.x[0]:.2f}')",
             "plt.axvline(res2.x[0], color='green', ls='--', label=f'from x0=10 -> {res2.x[0]:.2f}')",
             "plt.legend();"),
    ]


def course3_ex3_starter() -> list[dict]:
    return [
        md("# Exercise 3 — Grand Finale Lab (15 min)",
           "",
           "**Mission.** Load a messy stock-prices CSV, clean it with pandas, compute a 7-day moving average with NumPy, and plot price + MA together.",
           "",
           "Constraints:",
           "- No looping over rows.",
           "- Use `shared.data_utils.load_dataset('stock-prices')` to fetch the data."),
        code(
            "import sys, pathlib",
            "p = pathlib.Path.cwd()",
            "while not (p / 'pyproject.toml').exists() and p != p.parent:",
            "    p = p.parent",
            "if str(p) not in sys.path:",
            "    sys.path.insert(0, str(p))",
             "import numpy as np",
             "import pandas as pd",
             "import matplotlib.pyplot as plt",
             "from shared.data_utils import load_dataset",
             "rng = np.random.default_rng(0)",
             "",
             "df = load_dataset('stock-prices')",
             "# Inject synthetic NaNs so there is something to clean.",
             "mask = rng.random(len(df)) < 0.05",
             "df.loc[mask, df.columns[1]] = np.nan",
             "df.head()"),
        md("**Step 1.** Inspect: how many NaNs are there in the price column? What is the dtype of the date column?"),
        code("# your code here"),
        md("**Step 2.** Parse the date column to `datetime` and sort the DataFrame chronologically."),
        code("# your code here"),
        md("**Step 3.** Fill the NaN prices using forward-fill (use the previous valid price)."),
        code("# your code here"),
        md("**Step 4.** Using NumPy only (`np.convolve` or manual stride logic), compute the 7-day moving average of the price."),
        code("# your code here"),
        md("**Step 5.** Plot price and moving average together with date on the x-axis."),
        code("# your code here"),
    ]


def course3_ex3_solution() -> list[dict]:
    return [
        md("# Exercise 3 — Grand Finale Solution"),
        code(
            "import sys, pathlib",
            "p = pathlib.Path.cwd()",
            "while not (p / 'pyproject.toml').exists() and p != p.parent:",
            "    p = p.parent",
            "if str(p) not in sys.path:",
            "    sys.path.insert(0, str(p))",
             "import numpy as np",
             "import pandas as pd",
             "import matplotlib.pyplot as plt",
             "from shared.data_utils import load_dataset",
             "rng = np.random.default_rng(0)",
             "",
             "df = load_dataset('stock-prices')",
             "PRICE = df.columns[1]   # second column = closing price",
             "DATE = df.columns[0]",
             "mask = rng.random(len(df)) < 0.05",
             "df.loc[mask, PRICE] = np.nan",
             "print('shape:', df.shape, ' price col:', PRICE)"),
        md("**Step 1.** Inspect."),
        code("print('NaNs in price:', df[PRICE].isna().sum())",
             "print('date dtype  :', df[DATE].dtype)"),
        md("**Step 2.** Parse + sort."),
        code("df[DATE] = pd.to_datetime(df[DATE])",
             "df = df.sort_values(DATE).reset_index(drop=True)",
             "df.head()"),
        md("**Step 3.** Forward-fill."),
        code("df[PRICE] = df[PRICE].ffill()",
             "assert df[PRICE].isna().sum() == 0"),
        md("**Step 4.** 7-day moving average with NumPy."),
        code("window = 7",
             "kernel = np.ones(window) / window",
             "ma = np.convolve(df[PRICE].values, kernel, mode='valid')",
             "# Pad the front so lengths line up for plotting",
             "ma_full = np.concatenate([np.full(window - 1, np.nan), ma])",
             "print('ma len:', len(ma_full), '  df len:', len(df))"),
        md("**Step 5.** Plot."),
        code("fig, ax = plt.subplots(figsize=(10, 4))",
             "ax.plot(df[DATE], df[PRICE], label='price', alpha=0.5)",
             "ax.plot(df[DATE], ma_full, label='7-day MA', lw=2)",
             "ax.set_xlabel('date'); ax.set_ylabel(PRICE); ax.set_title('AAPL closing price + 7-day MA')",
             "ax.legend(); fig.autofmt_xdate();"),
    ]


# ============================================================================
# DRIVER
# ============================================================================

def combine(lecture, *exercise_pairs):
    """Concatenate lecture + (exercise, solution) pairs into one notebook.

    Each exercise/solution gets its own divider so the instructor can fold
    sections in JupyterLab. The bootstrap/import cell duplicated in every
    builder is harmless on re-run (sys.path insert is idempotent).
    """
    cells = list(lecture)
    cells.append(md("---", "", "# Exercises",
                    "",
                    "Each exercise below is followed by its solution.",
                    "Try to solve the tasks yourself before revealing the next cell."))
    for i, (starter, solution) in enumerate(exercise_pairs, 1):
        cells.append(md(f"---\n\n## Exercise {i}"))
        cells.extend(starter)
        cells.append(md(f"### Exercise {i} — Solution"))
        cells.extend(solution)
    return cells


NOTEBOOKS = [
    ("course-01-numpy/lecture.ipynb", lambda: combine(
        course1_lecture(),
        (course1_ex1_starter(), course1_ex1_solution()),
        (course1_ex2_starter(), course1_ex2_solution()),
        (course1_ex3_starter(), course1_ex3_solution()),
    )),
    ("course-02-pandas/lecture.ipynb", lambda: combine(
        course2_lecture(),
        (course2_ex1_starter(), course2_ex1_solution()),
        (course2_ex2_starter(), course2_ex2_solution()),
        (course2_ex3_starter(), course2_ex3_solution()),
    )),
    ("course-03-viz-scipy/lecture.ipynb", lambda: combine(
        course3_lecture(),
        (course3_ex1_starter(), course3_ex1_solution()),
        (course3_ex2_starter(), course3_ex2_solution()),
        (course3_ex3_starter(), course3_ex3_solution()),
    )),
]


def main() -> None:
    for rel, builder in NOTEBOOKS:
        path = WEEK1 / rel
        write_nb(path, builder())
        print(f"wrote {path.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
